server:
  port: 8888

spring:
  output.ansi.enabled: ALWAYS

  devtools.restart.enabled: true

  session:
    store-type: jdbc
    jdbc:
      table-name: CURR_SESSION
      initialize-schema: never
      # schema: classpath:schema-session.sql

  datasource:
    driverClassName: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:h2:~/test
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /system/h2-console

logging:
  level:
    jdbc: WARN

management:
  endpoints:
    web:
      base-path: /system/actuator
