server:
  port: 8888

spring:
  output.ansi.enabled: ALWAYS

  session:
    store-type: jdbc
    jdbc:
      schema: classpath:schema-session.sql
      table-name: CURR_SESSION

  h2.console:
      enabled: true

  datasource:
    driverClassName: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:h2:~/test
    username: sa
    password:
