CREATE TABLE CURR_SESSION (
	PRIMARY_ID CHAR(256) NOT NULL,
	SESSION_ID CHAR(256) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT CURR_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX CURR_SESSION_IX1 ON CURR_SESSION (SESSION_ID);
CREATE INDEX CURR_SESSION_IX2 ON CURR_SESSION (EXPIRY_TIME);
CREATE INDEX CURR_SESSION_IX3 ON CURR_SESSION (PRINCIPAL_NAME);

CREATE TABLE CURR_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(256) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES LONGVARBINARY NOT NULL,
	CONSTRAINT CURR_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT CURR_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES CURR_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
