CREATE TABLE CBMS_CURR_SESSION (
	PRIMARY_ID CHAR(256) NOT NULL,
	SESSION_ID CHAR(256) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT CBMS_CURR_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX CBMS_CURR_SESSION_IX1 ON CBMS_CURR_SESSION (SESSION_ID);
CREATE INDEX CBMS_CURR_SESSION_IX2 ON CBMS_CURR_SESSION (EXPIRY_TIME);
CREATE INDEX CBMS_CURR_SESSION_IX3 ON CBMS_CURR_SESSION (PRINCIPAL_NAME);

CREATE TABLE CBMS_CURR_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(256) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES LONGVARBINARY NOT NULL,
	CONSTRAINT CBMS_CURR_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT CBMS_CURR_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES CBMS_CURR_SESSION(PRIMARY_ID) ON DELETE CASCADE
);


CREATE SEQUENCE SQ_CBMS_BBS_ID START WITH 1;

CREATE TABLE CBMS_BBS (
    ID INTEGER NOT NULL,
    CATEGORY VARCHAR(32),
    SUBJECT VARCHAR(512),
    CONTENT CLOB,
    CREATER VARCHAR(32),
    CREATED TIMESTAMP,
    UPDATER VARCHAR(32),
    UPDATED TIMESTAMP,
    PRIMARY KEY(ID)
);
INSERT INTO CBMS_BBS VALUES (1, 'notice', '제목입니다.#1', '너무 길게..', 'admin', CURRENT_TIMESTAMP(), NULL, NULL);
INSERT INTO CBMS_BBS VALUES (2, 'notice', '제목입니다.#2', '너무 짧게...', 'judge', CURRENT_TIMESTAMP(), NULL, NULL);


CREATE TABLE CBMS_CODE (
    GRP VARCHAR(32) NOT NULL,
    CODE VARCHAR(32) NOT NULL,
    ORD INTEGER,
    VALUE VARCHAR(512),
    PRIMARY KEY(GRP, CODE)
);
INSERT INTO CBMS_CODE VALUES ('USER_ROLE', 'ADMIN', 0, '관리자');
INSERT INTO CBMS_CODE VALUES ('USER_ROLE', 'JUDGE', 0, '심의위원');
INSERT INTO CBMS_CODE VALUES ('USER_ROLE', 'OFFICER', 0, '본사담당자');
INSERT INTO CBMS_CODE VALUES ('USER_ROLE', 'WORKER', 0, '담당자');
INSERT INTO CBMS_CODE VALUES ('USER_ROLE', 'JOINER', 0, '승인대기자');


CREATE TABLE CBMS_USER (
    ID VARCHAR(32),
    PASSWORD VARCHAR(512),
    ROLE VARCHAR(32),
    NAME VARCHAR(128),
    MOBILE VARCHAR(16),
    EMAIL VARCHAR(256),
    TEL VARCHAR(16),
    APPROVED TIMESTAMP,
    PRIMARY KEY(ID)
);
INSERT INTO CBMS_USER VALUES ('admin', '{noop}1', 'ADMIN', '오두민', '01012344321', 'cbms.admin@knia.or.kr', '0237021234', CURRENT_TIMESTAMP());
